site_name: Zendikit
site_url: https://zendikit.work
site_description: The Zendikit main page(s)
site_author: Zendikit

docs_dir: src
site_dir: docs

theme:
  name: material
  palette:
    primary: white

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search

extra:
  social:
    - icon: fontawesome/solid/barcode
      link: https://zendikit.work
